def app

pipeline {
  agent any

  tools {maven "Maven 3.8.1"}

  stages {
    
        stage('Git') {
            steps {
                    checkout scm
                }
        }

        stage('Replace variables') {
            steps {
                dir('jumia_phone_validator/validator-backend/'){ 
                    script {
                        sh "sed -i 's+spring.datasource.url=.*+spring.datasource.url=jdbc:postgresql://${database_url}:${database_port}/${database_name}+g' src/main/resources/application.properties"
                        sh "sed -i 's+spring.datasource.username=.*+spring.datasource.username=${application_username}+g' src/main/resources/application.properties"
                        sh "sed -i 's+spring.datasource.password=.*+spring.datasource.password=${application_password}+g' src/main/resources/application.properties"
                        sh "cat src/main/resources/application.properties"
                    }
                }
            }
        }  

       stage('Tools & components') {
            steps {
                dir('jumia_phone_validator/validator-backend/'){ 
                    sh 'mvn --version'
                }
            }
        }       

        stage('Clean install') {
            steps {
                dir('jumia_phone_validator/validator-backend/'){ 
                        sh 'mvn clean install'
                    }
                }
        } 

        stage('Build image') {
            steps {
                dir('jumia_phone_validator/validator-backend/'){ 
                    script {
                        app = docker.build("johnylima/phone-validator-backend")
                    }
                }
            }
        } 

        stage('Test image') {
            steps {
                dir('jumia_phone_validator/validator-backend/'){ 
                    script {
                        app.inside {
                            sh 'echo "Tests passed"'
                        }
                    }
                }
            }
        }


        stage('Push image') {
            steps {
                dir('jumia_phone_validator/validator-backend/'){ 
                    script {
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                            app.push("${env.BUILD_NUMBER}")
                        }
                    }
                }
            }
        } 

        stage('Trigger update Phone-Validator-Manifest') {
            steps {
                dir('jumia_phone_validator/validator-frontend/'){ 
                    echo "triggering Phone-Validator-Backend-Manifest for updatemanifestjob"
                    build job: 'Phone-Validator-Backend-Manifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
                }   
            }
        }
  }
}